// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.5.0.0
//      SpecFlow Generator Version:3.5.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TrainTrain.Domain.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ReservationDePlacesAvecPriseEnCompteDesReductionsFeature : object, Xunit.IClassFixture<ReservationDePlacesAvecPriseEnCompteDesReductionsFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Reduction.feature"
#line hidden
        
        public ReservationDePlacesAvecPriseEnCompteDesReductionsFeature(ReservationDePlacesAvecPriseEnCompteDesReductionsFeature.FixtureData fixtureData, TrainTrain_Domain_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("fr-FR"), "Features", "Réservation de places avec prise en compte des réductions", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Train vide avec une réservation sans carte de réduction")]
        [Xunit.TraitAttribute("FeatureTitle", "Réservation de places avec prise en compte des réductions")]
        [Xunit.TraitAttribute("Description", "Train vide avec une réservation sans carte de réduction")]
        public virtual void TrainVideAvecUneReservationSansCarteDeReduction()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Train vide avec une réservation sans carte de réduction", null, tagsOfScenario, argumentsOfScenario);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlaces",
                            "Occupation"});
                table4.AddRow(new string[] {
                            "1",
                            "100",
                            "0%"});
                table4.AddRow(new string[] {
                            "2",
                            "100",
                            "0%"});
#line 4
testRunner.Given("un train avec les wagons suivants :", ((string)(null)), table4, "Etant donné ");
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nom",
                            "Prenom",
                            "CarteReduction"});
                table5.AddRow(new string[] {
                            "Toto",
                            "Titi",
                            ""});
#line 8
testRunner.When("on réserve pour ces voyageurs :", ((string)(null)), table5, "Quand ");
#line hidden
#line 11
testRunner.Then("la réservation est validée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 12
testRunner.And("le prix est de 50 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Train vide avec une réservation utilisant une carte 12-25")]
        [Xunit.TraitAttribute("FeatureTitle", "Réservation de places avec prise en compte des réductions")]
        [Xunit.TraitAttribute("Description", "Train vide avec une réservation utilisant une carte 12-25")]
        public virtual void TrainVideAvecUneReservationUtilisantUneCarte12_25()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Train vide avec une réservation utilisant une carte 12-25", null, tagsOfScenario, argumentsOfScenario);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlaces",
                            "Occupation"});
                table6.AddRow(new string[] {
                            "1",
                            "100",
                            "0%"});
                table6.AddRow(new string[] {
                            "2",
                            "100",
                            "0%"});
#line 15
testRunner.Given("un train avec les wagons suivants :", ((string)(null)), table6, "Etant donné ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nom",
                            "Prenom",
                            "CarteReduction"});
                table7.AddRow(new string[] {
                            "Toto",
                            "Titi",
                            "12-25"});
#line 19
testRunner.When("on réserve pour ces voyageurs :", ((string)(null)), table7, "Quand ");
#line hidden
#line 22
testRunner.Then("la réservation est validée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 23
testRunner.And("le prix est de 25 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Train vide avec une réservation utilisant une carte Senior")]
        [Xunit.TraitAttribute("FeatureTitle", "Réservation de places avec prise en compte des réductions")]
        [Xunit.TraitAttribute("Description", "Train vide avec une réservation utilisant une carte Senior")]
        public virtual void TrainVideAvecUneReservationUtilisantUneCarteSenior()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Train vide avec une réservation utilisant une carte Senior", null, tagsOfScenario, argumentsOfScenario);
#line 26
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlaces",
                            "Occupation"});
                table8.AddRow(new string[] {
                            "1",
                            "100",
                            "0%"});
                table8.AddRow(new string[] {
                            "2",
                            "100",
                            "0%"});
#line 27
testRunner.Given("un train avec les wagons suivants :", ((string)(null)), table8, "Etant donné ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nom",
                            "Prenom",
                            "CarteReduction"});
                table9.AddRow(new string[] {
                            "Toto",
                            "Titi",
                            "Senior"});
#line 31
testRunner.When("on réserve pour ces voyageurs :", ((string)(null)), table9, "Quand ");
#line hidden
#line 34
testRunner.Then("la réservation est validée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 35
testRunner.And("le prix est de 37,5 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Train vide avec une réservation utilisant une carte Grand voyageur")]
        [Xunit.TraitAttribute("FeatureTitle", "Réservation de places avec prise en compte des réductions")]
        [Xunit.TraitAttribute("Description", "Train vide avec une réservation utilisant une carte Grand voyageur")]
        public virtual void TrainVideAvecUneReservationUtilisantUneCarteGrandVoyageur()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Train vide avec une réservation utilisant une carte Grand voyageur", null, tagsOfScenario, argumentsOfScenario);
#line 38
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlaces",
                            "Occupation"});
                table10.AddRow(new string[] {
                            "1",
                            "100",
                            "0%"});
                table10.AddRow(new string[] {
                            "2",
                            "100",
                            "0%"});
#line 39
testRunner.Given("un train avec les wagons suivants :", ((string)(null)), table10, "Etant donné ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nom",
                            "Prenom",
                            "CarteReduction"});
                table11.AddRow(new string[] {
                            "Toto",
                            "Titi",
                            "Grand Voyageur"});
#line 43
testRunner.When("on réserve pour ces voyageurs :", ((string)(null)), table11, "Quand ");
#line hidden
#line 46
testRunner.Then("la réservation est validée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 47
testRunner.And("le prix est de 40 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Train vide avec une réservation pour chaque type de réduction et un sans")]
        [Xunit.TraitAttribute("FeatureTitle", "Réservation de places avec prise en compte des réductions")]
        [Xunit.TraitAttribute("Description", "Train vide avec une réservation pour chaque type de réduction et un sans")]
        public virtual void TrainVideAvecUneReservationPourChaqueTypeDeReductionEtUnSans()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Train vide avec une réservation pour chaque type de réduction et un sans", null, tagsOfScenario, argumentsOfScenario);
#line 49
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlaces",
                            "Occupation"});
                table12.AddRow(new string[] {
                            "1",
                            "100",
                            "0%"});
                table12.AddRow(new string[] {
                            "2",
                            "100",
                            "0%"});
#line 50
testRunner.Given("un train avec les wagons suivants :", ((string)(null)), table12, "Etant donné ");
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Nom",
                            "Prenom",
                            "CarteReduction"});
                table13.AddRow(new string[] {
                            "Toto",
                            "Titi",
                            "12-25"});
                table13.AddRow(new string[] {
                            "Tata",
                            "Tutu",
                            "Senior"});
                table13.AddRow(new string[] {
                            "Tete",
                            "Tyty",
                            "Grand Voyageur"});
                table13.AddRow(new string[] {
                            "Cast",
                            "Jean",
                            ""});
#line 54
testRunner.When("on réserve pour ces voyageurs :", ((string)(null)), table13, "Quand ");
#line hidden
#line 60
testRunner.Then("la réservation est validée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 61
testRunner.And("le prix est de 152,50 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ReservationDePlacesAvecPriseEnCompteDesReductionsFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ReservationDePlacesAvecPriseEnCompteDesReductionsFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
