// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.5.0.0
//      SpecFlow Generator Version:3.5.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TrainTrain.Domain.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class ReservationDePlacesDansPlusieursWagonUnTrainFeature : object, Xunit.IClassFixture<ReservationDePlacesDansPlusieursWagonUnTrainFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Train.feature"
#line hidden
        
        public ReservationDePlacesDansPlusieursWagonUnTrainFeature(ReservationDePlacesDansPlusieursWagonUnTrainFeature.FixtureData fixtureData, TrainTrain_Domain_Tests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("fr-FR"), "Features", "Réservation de places dans plusieurs wagon (un train)", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Train avec wagon 1 à 70% et wagon 2 vide, réservation de 4")]
        [Xunit.TraitAttribute("FeatureTitle", "Réservation de places dans plusieurs wagon (un train)")]
        [Xunit.TraitAttribute("Description", "Train avec wagon 1 à 70% et wagon 2 vide, réservation de 4")]
        public virtual void TrainAvecWagon1A70EtWagon2VideReservationDe4()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Train avec wagon 1 à 70% et wagon 2 vide, réservation de 4", null, tagsOfScenario, argumentsOfScenario);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlaces",
                            "Occupation"});
                table13.AddRow(new string[] {
                            "1",
                            "100",
                            "70%"});
                table13.AddRow(new string[] {
                            "2",
                            "100",
                            "0%"});
#line 4
  testRunner.Given("un train avec les wagons suivants :", ((string)(null)), table13, "Etant donné ");
#line hidden
#line 8
  testRunner.When("on réserve 4 places", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
#line 9
  testRunner.Then("la réservation est validée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 10
  testRunner.And("le prix est de 200 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlacesOccupees"});
                table14.AddRow(new string[] {
                            "1",
                            "70"});
                table14.AddRow(new string[] {
                            "2",
                            "4"});
#line 11
  testRunner.And("les wagons sont composés comme ceci :", ((string)(null)), table14, "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Train avec wagon 1 à 65% et wagon 2 vide, réservation de 10")]
        [Xunit.TraitAttribute("FeatureTitle", "Réservation de places dans plusieurs wagon (un train)")]
        [Xunit.TraitAttribute("Description", "Train avec wagon 1 à 65% et wagon 2 vide, réservation de 10")]
        public virtual void TrainAvecWagon1A65EtWagon2VideReservationDe10()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Train avec wagon 1 à 65% et wagon 2 vide, réservation de 10", null, tagsOfScenario, argumentsOfScenario);
#line 17
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlaces",
                            "Occupation"});
                table15.AddRow(new string[] {
                            "1",
                            "100",
                            "65%"});
                table15.AddRow(new string[] {
                            "2",
                            "100",
                            "0%"});
#line 18
  testRunner.Given("un train avec les wagons suivants :", ((string)(null)), table15, "Etant donné ");
#line hidden
#line 22
  testRunner.When("on réserve 10 places", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
#line 23
  testRunner.Then("la réservation est validée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 24
  testRunner.And("le prix est de 500 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlacesOccupees"});
                table16.AddRow(new string[] {
                            "1",
                            "65"});
                table16.AddRow(new string[] {
                            "2",
                            "10"});
#line 25
  testRunner.And("les wagons sont composés comme ceci :", ((string)(null)), table16, "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Train avec wagon 1 à 65% et wagon 2 à 66%, réservation de 10")]
        [Xunit.TraitAttribute("FeatureTitle", "Réservation de places dans plusieurs wagon (un train)")]
        [Xunit.TraitAttribute("Description", "Train avec wagon 1 à 65% et wagon 2 à 66%, réservation de 10")]
        public virtual void TrainAvecWagon1A65EtWagon2A66ReservationDe10()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Train avec wagon 1 à 65% et wagon 2 à 66%, réservation de 10", null, tagsOfScenario, argumentsOfScenario);
#line 30
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlaces",
                            "Occupation"});
                table17.AddRow(new string[] {
                            "1",
                            "100",
                            "65%"});
                table17.AddRow(new string[] {
                            "2",
                            "100",
                            "66%"});
#line 31
  testRunner.Given("un train avec les wagons suivants :", ((string)(null)), table17, "Etant donné ");
#line hidden
#line 35
  testRunner.When("on réserve 10 places", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
#line 36
  testRunner.Then("la réservation est annulée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlacesOccupees"});
                table18.AddRow(new string[] {
                            "1",
                            "65"});
                table18.AddRow(new string[] {
                            "2",
                            "66"});
#line 37
  testRunner.And("les wagons sont composés comme ceci :", ((string)(null)), table18, "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Train avec wagon 1 à 70% et wagon 2 à 72% et wagon 3 vide, réservation de 4")]
        [Xunit.TraitAttribute("FeatureTitle", "Réservation de places dans plusieurs wagon (un train)")]
        [Xunit.TraitAttribute("Description", "Train avec wagon 1 à 70% et wagon 2 à 72% et wagon 3 vide, réservation de 4")]
        public virtual void TrainAvecWagon1A70EtWagon2A72EtWagon3VideReservationDe4()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Train avec wagon 1 à 70% et wagon 2 à 72% et wagon 3 vide, réservation de 4", null, tagsOfScenario, argumentsOfScenario);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlaces",
                            "Occupation"});
                table19.AddRow(new string[] {
                            "1",
                            "100",
                            "70%"});
                table19.AddRow(new string[] {
                            "2",
                            "100",
                            "72%"});
                table19.AddRow(new string[] {
                            "3",
                            "100",
                            "1%"});
#line 43
  testRunner.Given("un train avec les wagons suivants :", ((string)(null)), table19, "Etant donné ");
#line hidden
#line 48
  testRunner.When("on réserve 4 places", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
#line 49
  testRunner.Then("la réservation est validée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 50
  testRunner.And("le prix est de 200 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlacesOccupees"});
                table20.AddRow(new string[] {
                            "1",
                            "70"});
                table20.AddRow(new string[] {
                            "2",
                            "72"});
                table20.AddRow(new string[] {
                            "3",
                            "5"});
#line 51
  testRunner.And("les wagons sont composés comme ceci :", ((string)(null)), table20, "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Train avec wagon 1 à 200 places dont 70 occupées et wagon 2 vide, réservation de " +
            "4")]
        [Xunit.TraitAttribute("FeatureTitle", "Réservation de places dans plusieurs wagon (un train)")]
        [Xunit.TraitAttribute("Description", "Train avec wagon 1 à 200 places dont 70 occupées et wagon 2 vide, réservation de " +
            "4")]
        public virtual void TrainAvecWagon1A200PlacesDont70OccupeesEtWagon2VideReservationDe4()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Train avec wagon 1 à 200 places dont 70 occupées et wagon 2 vide, réservation de " +
                    "4", null, tagsOfScenario, argumentsOfScenario);
#line 57
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlaces",
                            "Occupation"});
                table21.AddRow(new string[] {
                            "1",
                            "200",
                            "35%"});
                table21.AddRow(new string[] {
                            "2",
                            "200",
                            "0%"});
#line 58
  testRunner.Given("un train avec les wagons suivants :", ((string)(null)), table21, "Etant donné ");
#line hidden
#line 62
  testRunner.When("on réserve 4 places", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quand ");
#line hidden
#line 63
  testRunner.Then("la réservation est validée", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Alors ");
#line hidden
#line 64
  testRunner.And("le prix est de 200 €", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Et ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "Numero",
                            "NbPlacesOccupees"});
                table22.AddRow(new string[] {
                            "1",
                            "74"});
                table22.AddRow(new string[] {
                            "2",
                            "0"});
#line 65
  testRunner.And("les wagons sont composés comme ceci :", ((string)(null)), table22, "Et ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.5.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                ReservationDePlacesDansPlusieursWagonUnTrainFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                ReservationDePlacesDansPlusieursWagonUnTrainFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
